### ISSUE TITLE
Custom item types

### ISSUE THREAD

**Issue by hellbringer616** [hellbringer616/Strix-The-Realm#4]
Use Itemizer to create custom "Basic" (the defined smithing materials) weapon types for:

- [x] Dagger (Hoe)

- [ ] Bows

- [x] Sword

- [x] Mace (Pickaxe)

- [x] Wand (Spade)

As well as custom Armors for the following types:

**Robes**

- [x] Cloth

- [x] Enchanted

- [x] Mystic

**Leather**

- [x] Leather

- [x] Padded  Leather

- [x] Reinforced Leather

**Metal**
- [x] Bronze

- [x] Iron

- [x] Steel

**Comment by xxlio109** [comment]
Is there a complete pack?

**Comment by hellbringer616** [comment]
Complete pack? like a completed version of Strix? or a completed version of my list of items?

**Comment by xxlio109** [comment]
These configurations look interesting and I want to download the complete pack to play.

**Comment by xxlio109** [comment]
This is great, I like your settings.

**Comment by hellbringer616** [comment]
Feel free to create issues as you use the configs, i'll fix any bugs and can probably add extra features so long as they are inline with my over all goal :)

**Comment by hellbringer616** [comment]
Advanced features for Armor/Weapons on hold until NT-RPG|Itemizer integration is complete.
Item types will still be created but removed from the scope of 0.1.2

**Comment by hellbringer616** [comment]
latest git finishes this for now, likely will be reworked in 0.13.0 which i need NT-RPG API 2.0 to complete.
